# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Monospace
$wall = $HOME/.config/hypr/hyprlock/wallpapers/linux.jpg

general {
    hide_cursor = false
    no_fade_in = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $wall
    blur_passes = 0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# GREETINGS
label {
    monitor =
    text =Welcome!
    color = rgba(205, 214, 224, .75)
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = 165, 320
    halign = left
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(205, 214, 224, .75)
    font_size = 40
    font_family = JetBrainsMono Nerd Font
    position = 255, 240
    halign = left
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = Sunday, September 29
    color = rgba(205, 214, 224, .75)
    font_size = 20
    text_align = left
    font_family = JetBrainsMono Nerd Font
    position = 180, 175
    halign = left
    valign = center
}

# Profie-Photo
image {
    monitor =
    path = ~/.config/hypr/pfp.webp
    border_size = 1
    border_color = rgba(137, 180, 250, .75)
    size = 160
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 249, 25
    halign = left
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(255, 255, 255, .2)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 170, -140
    halign = left
    valign = center
}

# USER
label {
    monitor =
    text = cmd[update:0] echo "  $(whoami | tr a-z A-Z)"
    color = rgba(205, 214, 224, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 320, -140
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span foreground="##ffffffcc" letter_spacing="4000">  ENTER PASSWORD</span>
    hide_input = false
    position = 170, -220
    halign = left
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(23, 147, 209, 0.6)
}